name: "Dependency Review"
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4.2.3
        with:
          deny-licenses: Apache-2.0
          comment-summary-in-pr: always
